### ISSUE TITLE
I found the lake!

### ISSUE THREAD

**Issue by jakeasmith** [jwillyburns/lostlake#1]

**Comment by jwillyburns** [comment]
Lost Lake is two things, beyond my GitHub test repo.
1. A hipster bar/music venue in Denver that very recently was a legit dive
   bar with a fireplace (Lost Lake Lounge http://lost-lake.com/).
2. A classic, yet lesser-known, (very) cheap bear that is apparently now
   available in bottle (Lost Lake Beer http://www.lostlakebeer.com/).

Joel

**Comment by jakeasmith** [comment]
Ha! Very nice, sir.
